plugins {
    id 'com.android.application'
}

android {
    namespace 'com.magneo.compass'
    compileSdk 36

    defaultConfig {
        applicationId "com.magneo.compass"
        minSdk 22
        targetSdk 22
        versionCode 9
        versionName "0.2.7"
        ndk { abiFilters 'armeabi-v7a' }
        ndkVersion '27.0.12077973'
        externalNativeBuild {
            cmake { cppFlags "-std=c++14" }
        }
    }

    externalNativeBuild {
        cmake { path "src/main/cpp/CMakeLists.txt" }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
        coreLibraryDesugaringEnabled true
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.1.5'
    implementation 'com.squareup.okhttp3:okhttp:3.12.13'
    implementation 'commons-net:commons-net:3.11.1'
    implementation 'eu.agno3.jcifs:jcifs-ng:2.1.8'
    implementation 'com.emc.ecs:nfs-client:1.1.0'
    implementation 'io.github.webrtc-sdk:android:114.5735.06'
}
